In [1]:
import torch

In [3]:
x = torch.arange(1,12)
x

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
x.shape

torch.Size([11])

In [5]:
x = x.reshape(3,4)

RuntimeError: shape '[3, 4]' is invalid for input of size 11

In [7]:
x = torch.arange(0,12)
print(x)
x = x.reshape(3,4)
print(x)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [8]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [10]:
torch.tensor([[1,1,1,1],[1,1,1,1],[1,1,1,1]])

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [13]:
y = torch.arange(11,23).reshape(3,4)
y

tensor([[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]])

In [15]:
z = torch.cat((x,y),dim = 0)
z

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]])